import type { Tool, ToolCategory, ToolCategoryInfo } from '@/types';

export const toolCategories: ToolCategoryInfo[] = [
  { id: 'organize', name: 'Organize PDF', description: 'Arrange and manage PDF pages' },
  { id: 'optimize', name: 'Optimize PDF', description: 'Compress and optimize PDFs' },
  { id: 'convert-to-pdf', name: 'Convert to PDF', description: 'Convert files to PDF format' },
  { id: 'convert-from-pdf', name: 'Convert from PDF', description: 'Convert PDFs to other formats' },
  { id: 'edit', name: 'Edit PDF', description: 'Modify and enhance PDFs' },
  { id: 'security', name: 'PDF Security', description: 'Protect and secure PDFs' },
  { id: 'image-optimize', name: 'Optimize Image', description: 'Compress and enhance images' },
  { id: 'image-edit', name: 'Edit Image', description: 'Crop, resize, and modify images' },
  { id: 'image-convert', name: 'Convert Image', description: 'Convert between image formats' },
  { id: 'image-create', name: 'Create', description: 'Create memes and edit photos' },
];

export const tools: Tool[] = [
  // ═══════════════════════════════════════════════════════════
  // PDF TOOLS (Client-side with pdf-lib)
  // ═══════════════════════════════════════════════════════════

  // Organize PDF
  {
    id: 'merge',
    slug: 'merge-pdf',
    name: 'Merge PDF',
    description: 'Combine multiple PDFs into one file in your preferred order',
    icon: 'merge',
    color: '#E74C3C',
    category: 'organize',
    isPremium: false,
    isAI: false,
    processingType: 'client',
    maxFileSize: { free: 500, premium: 500 },
    acceptedFormats: ['.pdf'],
    outputFormat: 'pdf',
  },
  {
    id: 'split',
    slug: 'split-pdf',
    name: 'Split PDF',
    description: 'Separate PDF pages into individual files or custom ranges',
    icon: 'split',
    color: '#E74C3C',
    category: 'organize',
    isPremium: false,
    isAI: false,
    processingType: 'client',
    maxFileSize: { free: 500, premium: 500 },
    acceptedFormats: ['.pdf'],
    outputFormat: 'pdf',
  },
  {
    id: 'organize',
    slug: 'organize-pdf',
    name: 'Organize PDF',
    description: 'Reorder, delete, or rotate pages in your PDF',
    icon: 'organize',
    color: '#E74C3C',
    category: 'organize',
    isPremium: false,
    isAI: false,
    processingType: 'client',
    maxFileSize: { free: 500, premium: 500 },
    acceptedFormats: ['.pdf'],
    outputFormat: 'pdf',
  },
  {
    id: 'remove-pages',
    slug: 'remove-pages',
    name: 'Remove Pages',
    description: 'Delete specific pages from your PDF document',
    icon: 'remove',
    color: '#E74C3C',
    category: 'organize',
    isPremium: false,
    isAI: false,
    processingType: 'client',
    maxFileSize: { free: 500, premium: 500 },
    acceptedFormats: ['.pdf'],
    outputFormat: 'pdf',
  },
  {
    id: 'extract-pages',
    slug: 'extract-pages',
    name: 'Extract Pages',
    description: 'Extract specific pages from your PDF',
    icon: 'extract',
    color: '#E74C3C',
    category: 'organize',
    isPremium: false,
    isAI: false,
    processingType: 'client',
    maxFileSize: { free: 500, premium: 500 },
    acceptedFormats: ['.pdf'],
    outputFormat: 'pdf',
  },

  // Optimize PDF
  {
    id: 'compress',
    slug: 'compress-pdf',
    name: 'Compress PDF',
    description: 'Reduce PDF file size while maintaining quality',
    icon: 'compress',
    color: '#27AE60',
    category: 'optimize',
    isPremium: false,
    isAI: false,
    processingType: 'client',
    maxFileSize: { free: 500, premium: 500 },
    acceptedFormats: ['.pdf'],
    outputFormat: 'pdf',
  },

  // Convert to PDF
  {
    id: 'jpg-to-pdf',
    slug: 'jpg-to-pdf',
    name: 'JPG to PDF',
    description: 'Convert images to PDF documents',
    icon: 'image',
    color: '#F39C12',
    category: 'convert-to-pdf',
    isPremium: false,
    isAI: false,
    processingType: 'client',
    maxFileSize: { free: 500, premium: 500 },
    acceptedFormats: ['.jpg', '.jpeg', '.png', '.gif', '.bmp', '.webp'],
    outputFormat: 'pdf',
  },

  // Convert from PDF
  {
    id: 'pdf-to-jpg',
    slug: 'pdf-to-jpg',
    name: 'PDF to JPG',
    description: 'Convert PDF pages to JPG images',
    icon: 'image',
    color: '#F39C12',
    category: 'convert-from-pdf',
    isPremium: false,
    isAI: false,
    processingType: 'client',
    maxFileSize: { free: 500, premium: 500 },
    acceptedFormats: ['.pdf'],
    outputFormat: 'jpg',
  },

  // Edit PDF
  {
    id: 'edit',
    slug: 'edit-pdf',
    name: 'Edit PDF',
    description: 'Add text, images, shapes and annotations to PDF',
    icon: 'edit',
    color: '#9B59B6',
    category: 'edit',
    isPremium: false,
    isAI: false,
    processingType: 'client',
    maxFileSize: { free: 500, premium: 500 },
    acceptedFormats: ['.pdf'],
    outputFormat: 'pdf',
  },
  {
    id: 'rotate',
    slug: 'rotate-pdf',
    name: 'Rotate PDF',
    description: 'Rotate PDF pages to any orientation',
    icon: 'rotate',
    color: '#3498DB',
    category: 'edit',
    isPremium: false,
    isAI: false,
    processingType: 'client',
    maxFileSize: { free: 500, premium: 500 },
    acceptedFormats: ['.pdf'],
    outputFormat: 'pdf',
  },
  {
    id: 'page-numbers',
    slug: 'add-page-numbers',
    name: 'Add Page Numbers',
    description: 'Add page numbers to your PDF documents',
    icon: 'numbers',
    color: '#3498DB',
    category: 'edit',
    isPremium: false,
    isAI: false,
    processingType: 'client',
    maxFileSize: { free: 500, premium: 500 },
    acceptedFormats: ['.pdf'],
    outputFormat: 'pdf',
  },
  {
    id: 'watermark',
    slug: 'add-watermark',
    name: 'Add Watermark',
    description: 'Stamp text or image watermark on your PDF',
    icon: 'watermark',
    color: '#3498DB',
    category: 'edit',
    isPremium: false,
    isAI: false,
    processingType: 'client',
    maxFileSize: { free: 500, premium: 500 },
    acceptedFormats: ['.pdf'],
    outputFormat: 'pdf',
  },
  {
    id: 'crop',
    slug: 'crop-pdf',
    name: 'Crop PDF',
    description: 'Crop margins and resize PDF pages',
    icon: 'crop',
    color: '#3498DB',
    category: 'edit',
    isPremium: false,
    isAI: false,
    processingType: 'client',
    maxFileSize: { free: 500, premium: 500 },
    acceptedFormats: ['.pdf'],
    outputFormat: 'pdf',
  },

  // Security
  {
    id: 'protect',
    slug: 'protect-pdf',
    name: 'Protect PDF',
    description: 'Encrypt PDF with password protection',
    icon: 'lock',
    color: '#1ABC9C',
    category: 'security',
    isPremium: false,
    isAI: false,
    processingType: 'client',
    maxFileSize: { free: 500, premium: 500 },
    acceptedFormats: ['.pdf'],
    outputFormat: 'pdf',
  },
  {
    id: 'unlock',
    slug: 'unlock-pdf',
    name: 'Unlock PDF',
    description: 'Remove password protection from PDF',
    icon: 'unlock',
    color: '#1ABC9C',
    category: 'security',
    isPremium: false,
    isAI: false,
    processingType: 'client',
    maxFileSize: { free: 500, premium: 500 },
    acceptedFormats: ['.pdf'],
    outputFormat: 'pdf',
  },
  {
    id: 'sign',
    slug: 'sign-pdf',
    name: 'Sign PDF',
    description: 'Add digital signatures to your PDF',
    icon: 'signature',
    color: '#1ABC9C',
    category: 'security',
    isPremium: false,
    isAI: false,
    processingType: 'client',
    maxFileSize: { free: 500, premium: 500 },
    acceptedFormats: ['.pdf'],
    outputFormat: 'pdf',
  },
  {
    id: 'redact',
    slug: 'redact-pdf',
    name: 'Redact PDF',
    description: 'Permanently remove sensitive information',
    icon: 'redact',
    color: '#1ABC9C',
    category: 'security',
    isPremium: false,
    isAI: false,
    processingType: 'client',
    maxFileSize: { free: 500, premium: 500 },
    acceptedFormats: ['.pdf'],
    outputFormat: 'pdf',
  },

  // ═══════════════════════════════════════════════════════════
  // IMAGE TOOLS (Client-side with Canvas API)
  // ═══════════════════════════════════════════════════════════

  // Optimize Image
  {
    id: 'compress-image',
    slug: 'compress-image',
    name: 'Compress Image',
    description: 'Compress JPG, PNG, and WEBP while maintaining quality',
    icon: 'compress',
    color: '#3498DB',
    category: 'image-optimize',
    isPremium: false,
    isAI: false,
    processingType: 'client',
    maxFileSize: { free: 500, premium: 500 },
    acceptedFormats: ['.jpg', '.jpeg', '.png', '.webp'],
    outputFormat: 'original',
  },

  // Edit Image
  {
    id: 'resize-image',
    slug: 'resize-image',
    name: 'Resize Image',
    description: 'Resize images by percentage or pixel dimensions',
    icon: 'resize',
    color: '#9B59B6',
    category: 'image-edit',
    isPremium: false,
    isAI: false,
    processingType: 'client',
    maxFileSize: { free: 500, premium: 500 },
    acceptedFormats: ['.jpg', '.jpeg', '.png', '.gif', '.webp'],
    outputFormat: 'original',
  },
  {
    id: 'crop-image',
    slug: 'crop-image',
    name: 'Crop Image',
    description: 'Crop images with pixel precision or visual editor',
    icon: 'crop',
    color: '#9B59B6',
    category: 'image-edit',
    isPremium: false,
    isAI: false,
    processingType: 'client',
    maxFileSize: { free: 500, premium: 500 },
    acceptedFormats: ['.jpg', '.jpeg', '.png', '.gif', '.webp'],
    outputFormat: 'original',
  },
  {
    id: 'rotate-image',
    slug: 'rotate-image',
    name: 'Rotate Image',
    description: 'Rotate multiple images at once',
    icon: 'rotate',
    color: '#9B59B6',
    category: 'image-edit',
    isPremium: false,
    isAI: false,
    processingType: 'client',
    maxFileSize: { free: 500, premium: 500 },
    acceptedFormats: ['.jpg', '.jpeg', '.png', '.gif', '.webp'],
    outputFormat: 'original',
  },
  {
    id: 'watermark-image',
    slug: 'watermark-image',
    name: 'Watermark Image',
    description: 'Add text or image watermark to your photos',
    icon: 'watermark',
    color: '#9B59B6',
    category: 'image-edit',
    isPremium: false,
    isAI: false,
    processingType: 'client',
    maxFileSize: { free: 500, premium: 500 },
    acceptedFormats: ['.jpg', '.jpeg', '.png', '.webp'],
    outputFormat: 'original',
  },
  {
    id: 'flip-image',
    slug: 'flip-image',
    name: 'Flip Image',
    description: 'Flip images horizontally or vertically',
    icon: 'flip',
    color: '#9B59B6',
    category: 'image-edit',
    isPremium: false,
    isAI: false,
    processingType: 'client',
    maxFileSize: { free: 500, premium: 500 },
    acceptedFormats: ['.jpg', '.jpeg', '.png', '.gif', '.webp'],
    outputFormat: 'original',
  },

  // Convert Image
  {
    id: 'convert-to-jpg',
    slug: 'convert-to-jpg',
    name: 'Convert to JPG',
    description: 'Convert PNG, GIF, WEBP, BMP to JPG',
    icon: 'image',
    color: '#E67E22',
    category: 'image-convert',
    isPremium: false,
    isAI: false,
    processingType: 'client',
    maxFileSize: { free: 500, premium: 500 },
    acceptedFormats: ['.png', '.gif', '.webp', '.bmp'],
    outputFormat: 'jpg',
  },
  {
    id: 'convert-to-png',
    slug: 'convert-to-png',
    name: 'Convert to PNG',
    description: 'Convert JPG, GIF, WEBP, BMP to PNG',
    icon: 'image',
    color: '#E67E22',
    category: 'image-convert',
    isPremium: false,
    isAI: false,
    processingType: 'client',
    maxFileSize: { free: 500, premium: 500 },
    acceptedFormats: ['.jpg', '.jpeg', '.gif', '.webp', '.bmp'],
    outputFormat: 'png',
  },
  {
    id: 'convert-to-webp',
    slug: 'convert-to-webp',
    name: 'Convert to WEBP',
    description: 'Convert JPG, PNG, GIF to WEBP format',
    icon: 'image',
    color: '#E67E22',
    category: 'image-convert',
    isPremium: false,
    isAI: false,
    processingType: 'client',
    maxFileSize: { free: 500, premium: 500 },
    acceptedFormats: ['.jpg', '.jpeg', '.png', '.gif'],
    outputFormat: 'webp',
  },
  {
    id: 'svg-to-png',
    slug: 'svg-to-png',
    name: 'SVG to PNG',
    description: 'Convert SVG vector files to PNG images',
    icon: 'image',
    color: '#E67E22',
    category: 'image-convert',
    isPremium: false,
    isAI: false,
    processingType: 'client',
    maxFileSize: { free: 500, premium: 500 },
    acceptedFormats: ['.svg'],
    outputFormat: 'png',
  },
  {
    id: 'heic-to-jpg',
    slug: 'heic-to-jpg',
    name: 'HEIC to JPG',
    description: 'Convert iPhone HEIC photos to JPG',
    icon: 'image',
    color: '#E67E22',
    category: 'image-convert',
    isPremium: false,
    isAI: false,
    processingType: 'client',
    maxFileSize: { free: 500, premium: 500 },
    acceptedFormats: ['.heic', '.heif'],
    outputFormat: 'jpg',
  },

  // Create
  {
    id: 'photo-editor',
    slug: 'photo-editor',
    name: 'Photo Editor',
    description: 'Edit photos with filters, adjustments, and effects',
    icon: 'edit',
    color: '#E91E63',
    category: 'image-create',
    isPremium: false,
    isAI: false,
    processingType: 'client',
    maxFileSize: { free: 500, premium: 500 },
    acceptedFormats: ['.jpg', '.jpeg', '.png', '.webp'],
    outputFormat: 'original',
  },
  {
    id: 'meme-generator',
    slug: 'meme-generator',
    name: 'Meme Generator',
    description: 'Create memes with custom text and images',
    icon: 'meme',
    color: '#E91E63',
    category: 'image-create',
    isPremium: false,
    isAI: false,
    processingType: 'client',
    maxFileSize: { free: 500, premium: 500 },
    acceptedFormats: ['.jpg', '.jpeg', '.png', '.webp'],
    outputFormat: 'jpg',
  },
  {
    id: 'collage-maker',
    slug: 'collage-maker',
    name: 'Collage Maker',
    description: 'Create beautiful photo collages',
    icon: 'collage',
    color: '#E91E63',
    category: 'image-create',
    isPremium: false,
    isAI: false,
    processingType: 'client',
    maxFileSize: { free: 500, premium: 500 },
    acceptedFormats: ['.jpg', '.jpeg', '.png', '.webp'],
    outputFormat: 'jpg',
  },
  {
    id: 'gif-maker',
    slug: 'gif-maker',
    name: 'GIF Maker',
    description: 'Create animated GIFs from images',
    icon: 'gif',
    color: '#E91E63',
    category: 'image-create',
    isPremium: false,
    isAI: false,
    processingType: 'client',
    maxFileSize: { free: 500, premium: 500 },
    acceptedFormats: ['.jpg', '.jpeg', '.png', '.webp'],
    outputFormat: 'gif',
  },
];

export const getToolBySlug = (slug: string): Tool | undefined => {
  return tools.find(tool => tool.slug === slug);
};

export const getToolsByCategory = (category: ToolCategory): Tool[] => {
  return tools.filter(tool => tool.category === category);
};

export const getPopularTools = (): Tool[] => {
  const popularIds = ['merge', 'compress', 'pdf-to-jpg', 'compress-image', 'resize-image', 'convert-to-jpg', 'photo-editor', 'meme-generator'];
  return tools.filter(tool => popularIds.includes(tool.id));
};

export const getPDFTools = (): Tool[] => {
  return tools.filter(tool => !tool.category.startsWith('image'));
};

export const getImageTools = (): Tool[] => {
  return tools.filter(tool => tool.category.startsWith('image'));
};
